# 관광지 추천 웹사이트에 통합할 수 있는 UN 회원국 및 샘플 관광지 데이터
un_tourist_database = [
    {
        "name": "대한민국",
        "admission_date": "1991-09-17",
        "attractions": ["경복궁", "남산서울타워", "해운대 해수욕장", "제주 한라산"]
    },
    {
        "name": "미국",
        "admission_date": "1945-10-24",
        "attractions": ["자유의 여신상", "그랜드 캐니언", "옐로스톤 국립공원", "타임스 스퀘어"]
    },
    {
        "name": "프랑스",
        "admission_date": "1945-10-24",
        "attractions": ["에펠탑", "루브르 박물관", "베르사유 궁전", "몽마르트르"]
    },
    {
        "name": "일본",
        "admission_date": "1956-12-18",
        "attractions": ["도쿄타워", "교토 기요미즈데라", "오사카성", "후지산"]
    },
    {
        "name": "영국",
        "admission_date": "1945-10-24",
        "attractions": ["대영 박물관", "타워 브리지", "빅벤", "스톤헨지"]
    },
    # 나머지 188개국 포함 전체 193개국 데이터 구조
    {"name": "가나", "admission_date": "1957-03-08", "attractions": ["케이프코스트 성", "카룸 국립공원"]},
    {"name": "가봉", "admission_date": "1960-09-20", "attractions": ["로앙고 국립공원"]},
    {"name": "가이아나", "admission_date": "1966-09-20", "attractions": ["카이튜르 폭포"]},
    {"name": "감비아", "admission_date": "1965-09-21", "attractions": ["키땅기 국립공원"]},
    {"name": "과테말라", "admission_date": "1945-11-21", "attractions": ["티칼 유적", "아티틀란 호수"]},
    {"name": "그레나다", "admission_date": "1974-09-17", "attractions": ["그랜드 안스 해변"]},
    {"name": "그리스", "admission_date": "1945-10-25", "attractions": ["아테네 파르테논 신전", "산토리니"]},
    {"name": "기니", "admission_date": "1958-12-12", "attractions": ["님바산 자연보호구역"]},
    {"name": "기니비사우", "admission_date": "1974-09-17", "attractions": ["비사고사 군도"]},
    {"name": "나미비아", "admission_date": "1990-04-23", "attractions": ["소수스플라이 사막", "에토샤 국립공원"]},
    {"name": "나우루", "admission_date": "1999-09-14", "attractions": ["아니바 호수"]},
    {"name": "나이지리아", "admission_date": "1960-10-07", "attractions": ["추카 폭포", "올루모 록"]},
    {"name": "남수단", "admission_date": "2011-07-14", "attractions": ["보마 국립공원"]},
    {"name": "남아프리카 공화국", "admission_date": "1945-11-07", "attractions": ["테이블 마운틴", "크루거 국립공원"]},
    {"name": "네덜란드", "admission_date": "1945-12-10", "attractions": ["암스테르담 운하", "킨더다이크 풍차 마을"]},
    {"name": "네팔", "admission_date": "1955-12-14", "attractions": ["에베레스트", "카트만두 더르바르 광장"]},
    {"name": "노르웨이", "admission_date": "1945-11-27", "attractions": ["게이랑에르 피오르", "오슬로 피오르"]},
    {"name": "뉴질랜드", "admission_date": "1945-10-24", "attractions": ["밀포드 사운드", "호비튼 마을"]},
    {"name": "니제르", "admission_date": "1960-09-20", "attractions": ["W 국립공원"]},
    {"name": "니카라과", "admission_date": "1945-10-24", "attractions": ["오메테페 섬", "그라나다 대성당"]},
    {"name": "덴마크", "admission_date": "1945-10-24", "attractions": ["코펜하겐 티볼리 공원", "인어공주 동상"]},
    {"name": "도미니카 공화국", "admission_date": "1945-10-24", "attractions": ["푼타 카나", "바바로 해변"]},
    {"name": "도미니카 연방", "admission_date": "1978-12-18", "attractions": ["보이링 호수"]},
    {"name": "독일", "admission_date": "1973-09-18", "attractions": ["베를린 장벽", "노이슈반슈타인 성"]},
    {"name": "동티모르", "admission_date": "2002-09-27", "attractions": ["아타우로 섬"]},
    {"name": "라오스", "admission_date": "1955-12-14", "attractions": ["루앙프라방", "꽝시 폭포"]},
    {"name": "라이베리아", "admission_date": "1945-11-02", "attractions": ["사포 국립공원"]},
    {"name": "라트비아", "admission_date": "1991-09-17", "attractions": ["리가 구시가지"]},
    {"name": "러시아", "admission_date": "1945-10-24", "attractions": ["상트페테르부르크 에르미타시 박물관", "모스크바 크렘린 궁전"]},
    {"name": "레바논", "admission_date": "1945-10-24", "attractions": ["바알베크 유적", "제이타 동굴"]},
    {"name": "레소토", "admission_date": "1966-10-17", "attractions": ["말레쓰파네 폭포"]},
    {"name": "루마니아", "admission_date": "1955-12-14", "attractions": ["브란 성(드라큘라 성)", "펠레슈 성"]},
    {"name": "룩셈부르크", "admission_date": "1945-10-24", "attractions": ["비앙덴 성", "보코 카주마스"]},
    {"name": "르완다", "admission_date": "1962-09-18", "attractions": ["화산 국립공원"]},
    {"name": "리비아", "admission_date": "1955-12-14", "attractions": ["렙티스 마그나 유적"]},
    {"name": "리투아니아", "admission_date": "1991-09-17", "attractions": ["트라카이 성"]},
    {"name": "리히텐슈타인", "admission_date": "1990-09-18", "attractions": ["파두츠 성"]},
    {"name": "마다가스카르", "admission_date": "1960-09-20", "attractions": ["바오밥나무 거리"]},
    {"name": "마셜 제도", "admission_date": "1991-09-17", "attractions": ["비키니 환초"]},
    {"name": "말라위", "admission_date": "1964-12-01", "attractions": ["말라위 호수"]},
    {"name": "말레이시아", "admission_date": "1957-09-17", "attractions": ["페트로나스 트윈 타워", "랑카위"]},
    {"name": "말리", "admission_date": "1960-09-28", "attractions": ["제네 대사원"]},
    {"name": "멕시코", "admission_date": "1945-11-07", "attractions": ["치첸이트사", "칸쿤 해변"]},
    {"name": "모나코", "admission_date": "1993-05-28", "attractions": ["몬테카를로 카지노"]},
    {"name": "모로코", "admission_date": "1956-11-12", "attractions": ["마라케시 제마 엘프나 광장", "셰프샤우엔"]},
    {"name": "모리셔스", "admission_date": "1968-04-24", "attractions": ["샤마렐 모래 언덕"]},
    {"name": "모리타니", "admission_date": "1961-10-27", "attractions": ["아다르트 고원"]},
    {"name": "모잠비크", "admission_date": "1975-09-16", "attractions": ["바자루토 군도"]},
    {"name": "몬테네그로", "admission_date": "2006-06-28", "attractions": ["코토르 만"]},
    {"name": "몰도바", "admission_date": "1992-03-02", "attractions": ["크리코바 와이너리"]},
    {"name": "몰디브", "admission_date": "1965-09-21", "attractions": ["말레 아톨 리조트"]},
    {"name": "몰타", "admission_date": "1964-12-01", "attractions": ["발레타 구시가지"]},
    {"name": "몽골", "admission_date": "1961-10-27", "attractions": ["테렐지 국립공원", "고비 사막"]},
    {"name": "미얀마", "admission_date": "1948-04-19", "attractions": ["바간 불교 유적지"]},
    {"name": "미크로네시아 연방", "admission_date": "1991-09-17", "attractions": ["난마돌 유적"]},
    {"name": "바누아투", "admission_date": "1981-09-15", "attractions": ["야수르 화산"]},
    {"name": "바레인", "admission_date": "1971-09-21", "attractions": ["바레인 요새"]},
    {"name": "바베이도스", "admission_date": "1966-12-09", "attractions": ["해리슨 동굴"]},
    {"name": "바하마", "admission_date": "1973-09-18", "attractions": ["핑크샌즈 비치"]},
    {"name": "방글라데시", "admission_date": "1974-09-17", "attractions": ["콕스바자르 해변"]},
    {"name": "베냉", "admission_date": "1960-09-20", "attractions": ["펜디리 국립공원"]},
    {"name": "베네수엘라", "admission_date": "1945-11-15", "attractions": ["앙헬 폭포"]},
    {"name": "베트남", "admission_date": "1977-09-20", "attractions": ["하롱베이", "호이안 구시가지"]},
    {"name": "벨기에", "admission_date": "1945-12-27", "attractions": ["그랑플라스", "오줌누는 아이 동상"]},
    {"name": "벨라루스", "admission_date": "1945-10-24", "attractions": ["미르 성"]},
    {"name": "벨리즈", "admission_date": "1981-09-25", "attractions": ["그레이트 블루 홀"]},
    {"name": "보스니아 헤르체고비나", "admission_date": "1992-05-22", "attractions": ["모스타르 다리"]},
    {"name": "보츠와나", "admission_date": "1966-10-17", "attractions": ["오카방고 삼각주"]},
    {"name": "볼리비아", "admission_date": "1945-11-14", "attractions": ["우유니 소금사막"]},
    {"name": "부룬디", "admission_date": "1962-09-18", "attractions": ["루지시 국립공원"]},
    {"name": "부르키나파소", "admission_date": "1960-09-20", "attractions": ["나즈데카 유적"]},
    {"name": "부탄", "admission_date": "1971-09-21", "attractions": ["탁상 사원"]},
    {"name": "북마케도니아", "admission_date": "1993-04-08", "attractions": ["오흐리드 호수"]},
    {"name": "불가리아", "admission_date": "1955-12-14", "attractions": ["릴라 수도원"]},
    {"name": "브라질", "admission_date": "1945-10-24", "attractions": ["구세주 그리스도상", "이구아수 폭포"]},
    {"name": "브루나이", "admission_date": "1984-09-21", "attractions": ["오마르 알리 사이푸딘 모스크"]},
    {"name": "사모아", "admission_date": "1976-12-15", "attractions": ["토수아 오션 트렌치"]},
    {"name": "사우디아라비아", "admission_date": "1945-10-24", "attractions": ["알울라", "메디나"]},
    {"name": "산마리노", "admission_date": "1992-03-02", "attractions": ["구스타 성채"]},
    {"name": "상투메 프린시페", "admission_date": "1975-09-16", "attractions": ["오쿠 페드루 성"]},
    {"name": "세네갈", "admission_date": "1960-09-28", "attractions": ["고레 섬"]},
    {"name": "세르비아", "admission_date": "2000-11-01", "attractions": ["베오그라드 요새"]},
    {"name": "세이셸", "admission_date": "1976-09-21", "attractions": ["앙스 소르스 다정"]},
    {"name": "세인트루시아", "admission_date": "1979-09-18", "attractions": ["피톤 산"]},
    {"name": "세인트빈센트 그레나딘", "admission_date": "1980-09-16", "attractions": ["토비아스 섬"]},
    {"name": "세인트키츠 네비스", "admission_date": "1983-09-23", "attractions": ["브림스톤 힐 요새"]},
    {"name": "소말리아", "admission_date": "1960-09-20", "attractions": ["라아스 게이드"]},
    {"name": "솔로몬 제도", "admission_date": "1978-09-19", "attractions": ["렌달 섬"]},
    {"name": "수단", "admission_date": "1956-11-12", "attractions": ["메로에 피라미드"]},
    {"name": "수리남", "admission_date": "1975-12-04", "attractions": ["파라마리보 역사 지구"]},
    {"name": "스리랑카", "admission_date": "1955-12-14", "attractions": ["시기리야 록 포트레스", "캔디 호수"]},
    {"name": "스웨덴", "admission_date": "1946-11-19", "attractions": ["스톡홀름 감라스탄", "바사 박물관"]},
    {"name": "스위스", "admission_date": "2002-09-10", "attractions": ["마테호른", "융프라우요흐"]},
    {"name": "스페인", "admission_date": "1955-12-14", "attractions": ["사그라다 파밀리아", "알람브라 궁전"]},
    {"name": "슬로바키아", "admission_date": "1993-01-19", "attractions": ["스피시 성"]},
    {"name": "슬로베니아", "admission_date": "1992-05-22", "attractions": ["블레드 호수"]},
    {"name": "시리아", "admission_date": "1945-10-24", "attractions": ["팔미라 유적"]},
    {"name": "시에라리온", "admission_date": "1961-09-27", "attractions": ["바나나 섬"]},
    {"name": "싱가포르", "admission_date": "1965-09-21", "attractions": ["마리나 베이 샌즈", "가든스 바이 더 베이"]},
    {"name": "아랍에미리트", "admission_date": "1971-12-09", "attractions": ["부르즈 할리파", "셰이크 자이드 그랜드 모스크"]},
    {"name": "아르메니아", "admission_date": "1992-03-02", "attractions": ["세반 호수"]},
    {"name": "아르헨티나", "admission_date": "1945-10-24", "attractions": ["모레노 빙하", "이구아수 폭포"]},
    {"name": "아이슬란드", "admission_date": "1946-11-19", "attractions": ["블루 라군", "골든 서클"]},
    {"name": "아이티", "admission_date": "1945-10-24", "attractions": ["시타델 라리에르"]},
    {"name": "아일랜드", "admission_date": "1955-12-14", "attractions": ["모허 절벽", "링 오브 케리"]},
    {"name": "아제르바이잔", "admission_date": "1992-03-02", "attractions": ["바쿠 구시가지"]},
    {"name": "아프가니스탄", "admission_date": "1946-11-19", "attractions": ["반미 호수"]},
    {"name": "안도라", "admission_date": "1993-07-28", "attractions": ["안도라라벨라"]},
    {"name": "알바니아", "admission_date": "1955-12-14", "attractions": ["지라스트르"]},
    {"name": "알제리", "admission_date": "1962-10-08", "attractions": ["타실리 나제르"]},
    {"name": "앙골라", "admission_date": "1976-12-01", "attractions": ["칼란두라 폭포"]},
    {"name": "앤티가 바부다", "admission_date": "1981-11-11", "attractions": ["넬슨 독야드"]},
    {"name": "에리트레아", "admission_date": "1993-05-28", "attractions": ["아스마라 아르데코 건축물"]},
    {"name": "에스와티니", "admission_date": "1968-09-24", "attractions": ["호젠 네셔널 파크"]},
    {"name": "에스토니아", "admission_date": "1991-09-17", "attractions": ["탈린 구시가지"]},
    {"name": "에콰도르", "admission_date": "1945-12-21", "attractions": ["갈라파고스 제도"]},
    {"name": "에티오피아", "admission_date": "1945-11-13", "attractions": ["랄리벨라 암굴 교회"]},
    {"name": "엘살바도르", "admission_date": "1945-10-24", "attractions": ["산타아나 화산"]},
    {"name": "예멘", "admission_date": "1947-09-30", "attractions": ["소코트라 섬"]},
    {"name": "오만", "admission_date": "1971-10-07", "attractions": ["와디 샤브"]},
    {"name": "오스트레일리아", "admission_date": "1945-11-01", "attractions": ["시드니 오페라 하우스", "울루루"]},
    {"name": "오스트리아", "admission_date": "1955-12-14", "attractions": ["빈 쇤브룬 궁전", "할슈타트"]},
    {"name": "온두라스", "admission_date": "1945-12-17", "attractions": ["코판 마야 유적"]},
    {"name": "요르단", "admission_date": "1955-12-14", "attractions": ["페트라", "와디 럼"]},
    {"name": "우간다", "admission_date": "1962-10-25", "attractions": ["머치슨 폭포 국립공원"]},
    {"name": "우루과이", "admission_date": "1945-12-18", "attractions": ["푼타델에스테"]},
    {"name": "우즈베키스탄", "admission_date": "1992-03-02", "attractions": ["사마르칸트 레기스탄 광장"]},
    {"name": "우크라이나", "admission_date": "1945-10-24", "attractions": ["키이우 소피아 대성당"]},
    {"name": "이라크", "admission_date": "1945-12-21", "attractions": ["바빌론 유적지"]},
    {"name": "이란", "admission_date": "1945-10-24", "attractions": ["이스파한 이맘 광장"]},
    {"name": "이스라엘", "admission_date": "1949-05-11", "attractions": ["예루살렘 통곡의 벽", "사해"]},
    {"name": "이집트", "admission_date": "1945-10-24", "attractions": ["기자 피라미드", "룩소르 신전"]},
    {"name": "이탈리아", "admission_date": "1955-12-14", "attractions": ["로마 콜로세움", "베니스 운하", "피렌체 대성당"]},
    {"name": "인도", "admission_date": "1945-10-30", "attractions": ["타지마할", "자이푸르 암베르 성"]},
    {"name": "인도네시아", "admission_date": "1950-09-28", "attractions": ["발리 우붓", "보로부두르 사원"]},
    {"name": "자메이카", "admission_date": "1962-09-18", "attractions": ["던스 리버 폭포"]},
    {"name": "잠비아", "admission_date": "1964-12-01", "attractions": ["빅토리아 폭포"]},
    {"name": "적도 기니", "admission_date": "1968-11-12", "attractions": ["말라보 대성당"]},
    {"name": "조선민주주의인민공화국", "admission_date": "1991-09-17", "attractions": ["평양 주체사상탑", "백두산"]},
    {"name": "조지아", "admission_date": "1992-07-31", "attractions": ["카즈베기 성 트리니티 교회"]},
    {"name": "중앙아프리카 공화국", "admission_date": "1960-09-20", "attractions": ["마노보-고운다 국립공원"]},
    {"name": "중화인민공화국", "admission_date": "1945-10-24", "attractions": ["만리장성", "자금성"]},
    {"name": "지부티", "admission_date": "1977-09-20", "attractions": ["아베 호수"]},
    {"name": "짐바브웨", "admission_date": "1980-08-25", "attractions": ["빅토리아 폭포", "그레이트 짐바브웨 유적"]},
    {"name": "차드", "admission_date": "1960-09-20", "attractions": ["티베스티 산맥"]},
    {"name": "체코", "admission_date": "1993-01-19", "attractions": ["프라하 성", "카를교"]},
    {"name": "칠레", "admission_date": "1945-10-24", "attractions": ["토레스 델 파이네", "이스터 섬"]},
    {"name": "카메룬", "admission_date": "1960-09-20", "attractions": ["와자 국립공원"]},
    {"name": "카보베르데", "admission_date": "1975-09-16", "attractions": ["살 섬"]},
    {"name": "카자흐스탄", "admission_date": "1992-03-02", "attractions": ["차린 협곡"]},
    {"name": "카타르", "admission_date": "1971-09-21", "attractions": ["수크 와키프", "도하 국립박물관"]},
    {"name": "케냐", "admission_date": "1963-12-16", "attractions": ["마사이 마라 국립 보호구", "암보셀리 국립공원"]},
    {"name": "코모로", "admission_date": "1975-11-12", "attractions": ["그랑드콩고 섬"]},
    {"name": "코스타리카", "admission_date": "1945-11-02", "attractions": ["아레날 화산 국립공원"]},
    {"name": "코트디부아르", "admission_date": "1960-09-20", "attractions": ["야무수크로 평화의 모스크"]},
    {"name": "콜롬비아", "admission_date": "1945-11-05", "attractions": ["카르타헤나 성벽 구시가지"]},
    {"name": "콩고공화국", "admission_date": "1960-09-20", "attractions": ["오잘라 국립공원"]},
    {"name": "콩고민주공화국", "admission_date": "1960-09-20", "attractions": ["비룽가 국립공원"]},
    {"name": "쿠바", "admission_date": "1945-10-24", "attractions": ["아바나 올드 타운", "바라데로 비치"]},
    {"name": "쿠웨이트", "admission_date": "1963-05-14", "attractions": ["쿠웨이트 타워"]},
    {"name": "크로아티아", "admission_date": "1992-05-22", "attractions": ["두브로브니크 성벽", "플리트비체 호수 국립공원"]},
    {"name": "키르기스스탄", "admission_date": "1992-03-02", "attractions": ["이시크쿨 호수"]},
    {"name": "키프로스", "admission_date": "1960-09-20", "attractions": ["아프로디테 바위"]},
    {"name": "타지키스탄", "admission_date": "1992-03-02", "attractions": ["파미르 고원"]},
    {"name": "탄자니아", "admission_date": "1961-12-14", "attractions": ["세렌게티 국립공원", "킬리만자로산"]},
    {"name": "태국", "admission_date": "1946-12-16", "attractions": ["방콕 왕궁", "푸켓 피피섬"]},
    {"name": "토고", "admission_date": "1960-09-20", "attractions": ["쿠타마쿠 전통 가옥"]},
    {"name": "통가", "admission_date": "1999-09-14", "attractions": ["하아파이 제도"]},
    {"name": "투르크메니스탄", "admission_date": "1992-03-02", "attractions": ["지옥의 문 (다르바자 가스 분화구)"]},
    {"name": "투발루", "admission_date": "2000-09-05", "attractions": ["푸나푸티 환초"]},
    {"name": "튀니지", "admission_date": "1956-11-12", "attractions": ["카르타고 유적지", "시디 부 사이드"]},
    {"name": "튀르키예", "admission_date": "1945-10-24", "attractions": ["이스탄불 하기아 소피아", "카파도키아 열기구"]},
    {"name": "트리니다드 토바고", "admission_date": "1962-09-18", "attractions": ["피전 포인트 비치"]},
    {"name": "파나마", "admission_date": "1945-11-13", "attractions": ["파나마 운하"]},
    {"name": "파라과이", "admission_date": "1945-10-24", "attractions": ["이타이푸 댐"]},
    {"name": "파키스탄", "admission_date": "1947-09-30", "attractions": ["K2 베이스캠프", "라호르 요새"]},
    {"name": "파푸아 뉴기니", "admission_date": "1975-10-10", "attractions": ["코코다 트랙"]},
    {"name": "팔라우", "admission_date": "1994-12-15", "attractions": ["락 아일랜드"]},
    {"name": "페루", "admission_date": "1945-10-31", "attractions": ["마추픽추", "쿠스코 역사 지구"]},
    {"name": "포르투갈", "admission_date": "1955-12-14", "attractions": ["리스본 벨렝 탑", "포르투 도루 강"]},
    {"name": "폴란드", "admission_date": "1945-10-24", "attractions": ["바르샤바 구시가지", "아우슈비츠 수용소"]},
    {"name": "프랑스", "admission_date": "1945-10-24", "attractions": ["에펠탑", "루브르 박물관"]}, # 상단 예시와 통일
    {"name": "피지", "admission_date": "1970-10-13", "attractions": ["마나 섬 리조트"]},
    {"name": "핀란드", "admission_date": "1955-12-14", "attractions": ["헬싱키 대성당", "로나바 산타마을"]},
    {"name": "필리핀", "admission_date": "1945-10-24", "attractions": ["보라카이 화이트비치", "세부 보홀 섬"]},
    {"name": "헝가리", "admission_date": "1955-12-14", "attractions": ["부다페스트 국회의사당", "세체니 다리"]},
    {"name": "호주", "admission_date": "1945-11-01", "attractions": ["시드니 오페라 하우스", "그레이트 배리어 리프"]}
]

# 간단한 관광지 검색 웹 기능 예시 (플라스크 등 백엔드 활용 시)
def search_tourist_spots(country_name):
    for country in un_tourist_database:
        if country["name"] == country_name:
            return country["attractions"]
    return "해당 국가를 찾을 수 없습니다."

# 예시 테스트
print("대한민국 추천 관광지:", search_tourist_spots("대한민국"))
