un_tourist_database_70 = [
    {"name": "대한민국", "admission_date": "1991-09-17", "attractions": ["경복궁", "남산서울타워", "해운대 해수욕장", "제주 한라산"]},
    {"name": "조선민주주의인민공화국", "admission_date": "1991-09-17", "attractions": ["평양 주체사상탑", "백두산", "개성 역사유적지구", "묘향산"]},
    {"name": "미국", "admission_date": "1945-10-24", "attractions": ["자유의 여신상", "그랜드 캐니언", "옐로스톤 국립공원", "타임스 스퀘어"]},
    {"name": "프랑스", "admission_date": "1945-10-24", "attractions": ["에펠탑", "루브르 박물관", "베르사유 궁전", "몽마르트르"]},
    {"name": "일본", "admission_date": "1956-12-18", "attractions": ["도쿄타워", "교토 기요미즈데라", "오사카성", "후지산"]},
    {"name": "영국", "admission_date": "1945-10-24", "attractions": ["대영 박물관", "타워 브리지", "빅벤", "스톤헨지"]},
    {"name": "중화인민공화국", "admission_date": "1945-10-24", "attractions": ["만리장성", "자금성", "병마용갱", "계림 산수"]},
    {"name": "독일", "admission_date": "1973-09-18", "attractions": ["베를린 장벽", "노이슈반슈타인 성", "브란덴부르크 문"]},
    {"name": "러시아", "admission_date": "1945-10-24", "attractions": ["상트페테르부르크 에르미타시", "모스크바 크렘린 궁전", "바이칼 호수"]},
    {"name": "이탈리아", "admission_date": "1955-12-14", "attractions": ["로마 콜로세움", "베니스 운하", "피렌체 대성당", "밀라노 대성당"]},
    {"name": "스페인", "admission_date": "1955-12-14", "attractions": ["사그라다 파밀리아", "알람브라 궁전", "구엘 공원"]},
    {"name": "캐나다", "admission_date": "1945-11-09", "attractions": ["나이아가라 폭포", "밴프 국립공원", "밴쿠버 스탠리 파크"]},
    {"name": "호주", "admission_date": "1945-11-01", "attractions": ["시드니 오페라 하우스", "그레이트 배리어 리프", "울루루"]},
    {"name": "브라질", "admission_date": "1945-10-24", "attractions": ["구세주 그리스도상", "이구아수 폭포", "리오데자네이로 코파카바나"]},
    {"name": "인도", "admission_date": "1945-10-30", "attractions": ["타지마할", "자이푸르 암베르 성", "바라나시 갠지스강"]},
    {"name": "베트남", "admission_date": "1977-09-20", "attractions": ["하롱베이", "호이안 구시가지", "하노이 호안끼엠 호수"]},
    {"name": "태국", "admission_date": "1946-12-16", "attractions": ["방콕 왕궁", "푸켓 피피섬", "치앙마이 사원"]},
    {"name": "인도네시아", "admission_date": "1950-09-28", "attractions": ["발리 우붓", "보로부두르 사원", "코모도 국립공원"]},
    {"name": "싱가포르", "admission_date": "1965-09-21", "attractions": ["마리나 베이 샌즈", "가든스 바이 더 베이", "센토사 섬"]},
    {"name": "말레이시아", "admission_date": "1957-09-17", "attractions": ["페트로나스 트윈 타워", "랑카위", "페낭 기호지구"]},
    {"name": "필리핀", "admission_date": "1945-10-24", "attractions": ["보라카이 화이트비치", "세부 보홀 섬", "팔라완 엘니도"]},
    {"name": "튀르키예", "admission_date": "1945-10-24", "attractions": ["이스탄불 하기아 소피아", "카파도키아 열기구", "파묵칼레"]},
    {"name": "아랍에미리트", "admission_date": "1971-12-09", "attractions": ["부르즈 할리파", "셰이크 자이드 그랜드 모스크", "팜 주메이라"]},
    {"name": "사우디아라비아", "admission_date": "1945-10-24", "attractions": ["알울라", "디리야 유적지", "제다 알파케드"]},
    {"name": "이집트", "admission_date": "1945-10-24", "attractions": ["기자 피라미드", "룩소르 신전", "카이로 이집트 박물관"]},
    {"name": "남아프리카 공화국", "admission_date": "1945-11-07", "attractions": ["테이블 마운틴", "크루거 국립공원", "케이프타운 워터프런트"]},
    {"name": "멕시코", "admission_date": "1945-11-07", "attractions": ["치첸이트사", "칸쿤 해변", "메멕시코시티 소칼로"]},
    {"name": "아르헨티나", "admission_date": "1945-10-24", "attractions": ["모레노 빙하", "이구아수 폭포", "부에노스아이레스 보카"]},
    {"name": "그리스", "admission_date": "1945-10-25", "attractions": ["아테네 파르테논 신전", "산토리니", "미코노스"]},
    {"name": "스위스", "admission_date": "2002-09-10", "attractions": ["마테호른", "융프라우요흐", "루체른 호수"]},
    {"name": "네덜란드", "admission_date": "1945-12-10", "attractions": ["암스테르담 운하", "킨더다이크 풍차 마을", "반 고흐 미술관"]},
    {"name": "스웨덴", "admission_date": "1946-11-19", "attractions": ["스톡홀름 감라스탄", "바사 박물관", "스톡홀름 시청사"]},
    {"name": "노르웨이", "admission_date": "1945-11-27", "attractions": ["게이랑에르 피오르", "오슬로 피오르", "로포텐 제도"]},
    {"name": "덴마크", "admission_date": "1945-10-24", "attractions": ["코펜하겐 티볼리 공원", "인어공주 동상", "뉘하운"]},
    {"name": "오스트리아", "admission_date": "1955-12-14", "attractions": ["빈 쇤브룬 궁전", "할슈타트", "잘츠부르크 요새"]},
    {"name": "포르투갈", "admission_date": "1955-12-14", "attractions": ["리스본 벨렝 탑", "포르투 도루 강", "신트라 궁전"]},
    {"name": "아일랜드", "admission_date": "1955-12-14", "attractions": ["모허 절벽", "링 오브 케리", "더블린 기네스 스토어하우스"]},
    {"name": "체코", "admission_date": "1993-01-19", "attractions": ["프라하 성", "카를교", "체스키 크룸로프 구시가지"]},
    {"name": "폴란드", "admission_date": "1945-10-24", "attractions": ["바르샤바 구시가지", "아우슈비츠 수용소", "크라코프 중앙시장 광장"]},
    {"name": "헝가리", "admission_date": "1955-12-14", "attractions": ["부다페스트 국회의사당", "세체니 다리", "어부의 요새"]},
    {"name": "뉴질랜드", "admission_date": "1945-10-24", "attractions": ["밀포드 사운드", "호비튼 마을", "퀸즈타운 와카티푸 호수"]},
    {"name": "쿠바", "admission_date": "1945-10-24", "attractions": ["아바나 올드 타운", "바라데로 비치", "비냘레스 계곡"]},
    {"name": "페루", "admission_date": "1945-10-31", "attractions": ["마추픽추", "쿠스코 역사 지구", "나스카 라인"]},
    {"name": "칠레", "admission_date": "1945-10-24", "attractions": ["토레스 델 파이네", "이스터 섬", "아타카마 사막"]},
    {"name": "콜롬비아", "admission_date": "1945-11-05", "attractions": ["카르타헤나 성벽 구시가지", "보고타 몬세라테", "타이로나 국립공원"]},
    {"name": "이스라엘", "admission_date": "1949-05-11", "attractions": ["예루살렘 통곡의 벽", "사해", "텔아비브 해변"]},
    {"name": "카타르", "admission_date": "1971-09-21", "attractions": ["수크 와키프", "도하 국립박물관", "카타라 문화 마을"]},
    {"name": "요르단", "admission_date": "1955-12-14", "attractions": ["페트라", "와디 럼", "사해 바다"]},
    {"name": "모로코", "admission_date": "1956-11-12", "attractions": ["마라케시 제마 엘프나 광장", "셰프샤우엔", "페스 엘발리"]},
    {"name": "케냐", "admission_date": "1963-12-16", "attractions": ["마사이 마라 국립 보호구", "암보셀리 국립공원", "나이로비 국립공원"]},
    {"name": "탄자니아", "admission_date": "1961-12-14", "attractions": ["세렌게티 국립공원", "킬리만자로산", "잔지바르 스톤타운"]},
    {"name": "아이슬란드", "admission_date": "1946-11-19", "attractions": ["블루 라군", "골든 서클", "바트나요쿨 빙하"]},
    {"name": "크로아티아", "admission_date": "1992-05-22", "attractions": ["두브로브니크 성벽", "플리트비체 호수", "스플리트 디오클레티안 궁전"]},
    {"name": "핀란드", "admission_date": "1955-12-14", "attractions": ["헬싱키 대성당", "로바니에미 산타마을", "수오멘린나 요새"]},
    {"name": "벨기에", "admission_date": "1945-12-27", "attractions": ["브뤼셀 그랑플라스", "오줌누는 아이 동상", "브뤼헤 운하"]},
    {"name": "몽골", "admission_date": "1961-10-27", "attractions": ["테렐지 국립공원", "고비 사막", "울란바토르 수흐바토르 광장"]},
    {"name": "카자흐스탄", "admission_date": "1992-03-02", "attractions": ["차린 협곡", "빅 알마티 호수", "아스타나 바이테렌"]},
    {"name": "우즈베키스탄", "admission_date": "1992-03-02", "attractions": ["사마르칸트 레기스탄 광장", "부하라 아르크 성", "히바 이찬 칼라"]},
    {"name": "스리랑카", "admission_date": "1955-12-14", "attractions": ["시기리야 록 포트레스", "캔디 불치사", "누와라 엘리야 차밭"]},
    {"name": "네팔", "admission_date": "1955-12-14", "attractions": ["에베레스트", "카트만두 더르바르 광장", "포카라 페와 호수"]},
    {"name": "캄보디아", "admission_date": "1955-12-14", "attractions": ["앙코르 와트", "바이욘 사원", "톤레사프 호수"]},
    {"name": "몰디브", "admission_date": "1965-09-21", "attractions": ["말레 아톨 리조트", "바 아톨", "마푸시 섬"]},
    {"name": "오만", "admission_date": "1971-10-07", "attractions": ["와디 샤브", "무스카트 무트라 수크", "니즈와 요새"]},
    {"name": "에티오피아", "admission_date": "1945-11-13", "attractions": ["랄리벨라 암굴 교회", "심리엔 산맥", "액섬 오벨리스크"]},
    {"name": "나이지리아", "admission_date": "1960-10-07", "attractions": ["추카 폭포", "올루모 록", "레키 보호구역"]},
    {"name": "마다가스카르", "admission_date": "1960-09-20", "attractions": ["바오밥나무 거리", "칭기 드 베마라하", "이살로 국립공원"]},
    {"name": "모리셔스", "admission_date": "1968-04-24", "attractions": ["샤마렐 모래 언덕", "르모른 브라반", "일레 오 세프"]},
    {"name": "세이셸", "admission_date": "1976-09-21", "attractions": ["앙스 소르스 다정", "발레 드 메 국립공원", "빅토리아 시계탑"]},
    {"name": "짐바브웨", "admission_date": "1980-08-25", "attractions": ["빅토리아 폭포", "그레이트 짐바브웨 유적", "환게 국립공원"]},
    {"name": "피지", "admission_date": "1970-10-13", "attractions": ["마나 섬 리조트", "소소우 호수", "덴나라우 섬"]}
]

print(f"압축된 주요 국가 수: {len(un_tourist_database_70)}개")
